[main]
 #
placeholder     = "Search?.."
prompt          = ":> "
 #
icons-enabled   = false
layer           = overlay
keyboard-focus  = on-demand
 #
lines           = 9
tabs            = 4
inner-pad       = 16
 #
horizontal-pad  = 8
vertical-pad    = 8
[colors]
 #
background      = 111111cc
text            = 8c9bacdd
border          = 00000000
 #
prompt          = fdf3fdff
placeholder     = 8c9bacdd
 #
input           = bccdeeff
match		= bccdeeff
selection-match = bccdeeff
 #
selection       = 00000055
selection-text  = fdf3fdff

[border]
radius          = 0
